# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iFood', '0003_auto_20190311_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
